---
title: "Replicate"
author: "Grace A"
date: today
format: 
    html:
        code-fold: true
        theme: cosmo
number-sections: true
bibliography: 
    - ref.bib
    - refPackages.bib
csl: ecology.csl
knitr:
  opts_chunk:
    message: false
    warning: false
---

```{r}
library(ggplot2)
library(plotly)

anoxia <- read_csv("HW2/anoxia_jmt3_SL.csv")

#ð‘¦1t = âˆ’0.980
#(0.405) + 6.903 Â· 10âˆ’6
#(1.069Â·10âˆ’6) JanAprTNLoadt

#ð‘¦2t = âˆ’0.217
#(0.426) + 5.596 Â· 10âˆ’6
#(1.360Â·10âˆ’6) JanMað‘¦TNLoadt

Equ8 <- function(x){(-0.980 + 6.903)*((10^-6)*(anoxia$JanAprTNLoad))}
Equ9 <- function(x){(-0.217 + 5.596)*((10^-6)*(anoxia$JanMayTNLoad))}

```



```{r}
Ear <- ggplot(anoxia, aes(x = Year, y = EarlySummerAnoxicVol)) +
  geom_jitter(size = 0.6, alpha = 0.9, width = 0.2) +
  theme_light() + stat_function(fun = Equ8)
ggplotly(Ear, tooltip = c("y"))

Lat <- ggplot(anoxia, aes(x = Year, y = LateSummerAnoxicVol)) +
  geom_jitter(size = 0.6, alpha = 0.9, width = 0.2) +
  theme_light() + stat_function(fun = Equ9)
ggplotly(Lat, tooltip = c("y"))

ggplot(anoxia,aes(Year,EarlySummerAnoxicVol)) + geom_point(shape = 1) + geom_line(color="black") + xlab(label = "Year") + ylab(label = "Early Summer Volume (km^3)")

ggplot(anoxia,aes(Year,LateSummerAnoxicVol)) + geom_point(shape = 1) + geom_line(color="black") + xlab(label = "Year") + ylab(label = "Late Summer Volume (km^3)")
```


ggplot(anoxia,aes(Year,EarlySummerAnoxicVol)) + geom_line(color="blue", size=0.5) + 
  geom_smooth(method="lm", color = "dark red") + geom_hline(yintercept=0, linetype="dashed", color = "dark gray", size = 1) + xlab(label = "Year") + ylab(label = "Late Summer Volume (km^3)")


```{r}
library(rpart)
library(rpart.plot)
# classification
m0 = rpart(Year ~ ., data = anoxia)
rpart.plot(m0)
# regression
m1 = rpart(Petal.Width ~ ., 
           control = rpart.control(maxdepth = 2),
           data = anoxia)
rpart.plot(m1)
```